'use client'

import { useState } from 'react'
import { ArrowRight, BarChart3, Check, ChevronDown, FileText, Menu, Moon, Package, ReceiptText, Search, Settings2, ShieldCheck, ShoppingCart, Sparkles, Sun, Users, X, Zap } from 'lucide-react'
import { Button, buttonVariants } from '@/components/ui/button'
import { cn } from '@/lib/utils'

const manualUrl = 'https://blobs.vusercontent.net/blob/Manual%20de%20Usuario%20%E2%80%94%20AmaxTech-pEmpTwYGuYN6zjTZJyxin2VZbT1Pvp.pdf'
const faqs = [
  ['¿Qué incluye AmaxTech?', 'Una tienda digital con catálogo, carrito y solicitudes, además de un panel administrativo para productos, usuarios, precios, cotizaciones, solicitudes y facturación SENIAT.'],
  ['¿Puedo adaptar la tienda a mi negocio?', 'Sí. Configuras marca, logo, contactos, redes, textos de portada, enlaces de navegación, cotizaciones y datos fiscales desde el panel.'],
  ['¿El sistema sirve para equipos con varios usuarios?', 'Sí. Incluye roles personalizados y permisos por módulo para que cada persona vea y gestione únicamente lo que necesita.'],
]
const segments = [
  { icon: ShoppingCart, title: 'Tienda y catálogo', text: 'Una experiencia pública para descubrir productos, filtrar por categoría o marca, consultar fichas y armar un carrito.' },
  { icon: Users, title: 'Clientes y solicitudes', text: 'Cada cliente tiene su espacio, historial y seguimiento. Confirma por WhatsApp y recibe un ID único de solicitud.' },
  { icon: BarChart3, title: 'Panel de control', text: 'KPIs, ventas, tasas, inventario y productos más vendidos para decidir con información real.' },
  { icon: Package, title: 'Productos e inventario', text: 'Gestiona fotos, variantes, stock, costos, categorías, marcas, proveedores e importaciones por Excel.' },
  { icon: ReceiptText, title: 'Cotizaciones y facturación', text: 'Crea cotizaciones profesionales, conviértelas en solicitudes y emite facturas electrónicas con datos SENIAT.' },
  { icon: Settings2, title: 'Precios y configuración', text: 'Calcula el impacto de la tasa, aplica aumentos masivos con simulación y personaliza toda la tienda.' },
]

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [dark, setDark] = useState(true)
  const [faq, setFaq] = useState<number | null>(0)
  const [email, setEmail] = useState('')
  const [sent, setSent] = useState(false)
  const toggleTheme = () => { setDark(!dark); document.documentElement.classList.toggle('light', dark) }
  const submitLead = (e: React.FormEvent) => { e.preventDefault(); if (email) setSent(true) }

  return <main className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="sticky top-0 z-30 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
      <a href="#inicio" className="flex items-center gap-2 font-bold tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Zap /></span><span className="text-xl">amax<span className="text-primary">tech</span></span></a>
      <nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#producto">Plataforma</a><a href="#segmentos">Módulos</a><a href="#manual">Manual</a><a href="#precios">Planes</a></nav>
      <div className="hidden items-center gap-3 md:flex"><Button variant="ghost" onClick={toggleTheme} aria-label="Cambiar modo">{dark ? <Sun data-icon="inline-start" /> : <Moon data-icon="inline-start" />}{dark ? 'Modo claro' : 'Modo oscuro'}</Button><Button asChild><a href="#contacto">Solicitar demo <ArrowRight data-icon="inline-end" /></a></Button></div>
      <button aria-label={menuOpen ? 'Cerrar menú' : 'Abrir menú'} className="md:hidden" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
    </div>{menuOpen && <nav className="flex flex-col gap-4 border-t border-border px-5 py-5 text-sm md:hidden"><a href="#producto" onClick={() => setMenuOpen(false)}>Plataforma</a><a href="#segmentos" onClick={() => setMenuOpen(false)}>Módulos</a><a href="#manual" onClick={() => setMenuOpen(false)}>Manual</a><a href="#precios" onClick={() => setMenuOpen(false)}>Planes</a><Button asChild><a href="#contacto">Solicitar demo</a></Button></nav>}</header>

    <section id="inicio" className="mx-auto max-w-7xl px-5 pb-20 pt-20 lg:px-8 lg:pb-28 lg:pt-28"><div className="grid items-center gap-14 lg:grid-cols-[1fr_0.95fr]"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1.5 text-xs font-medium text-primary"><Sparkles data-icon="inline-start" /> Software comercial listo para vender</div><h1 className="max-w-2xl text-balance text-5xl font-semibold tracking-[-0.05em] sm:text-6xl lg:text-7xl">Tu tienda. Tu operación. <span className="text-primary">Todo conectado.</span></h1><p className="mt-6 max-w-xl text-pretty text-lg leading-relaxed text-muted-foreground">AmaxTech es la plataforma que convierte un catálogo en un negocio completo: vende, administra y factura desde un solo lugar.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" asChild><a href="#contacto">Quiero ver AmaxTech <ArrowRight data-icon="inline-end" /></a></Button><Button size="lg" variant="outline" asChild><a href="#segmentos">Explorar módulos</a></Button></div><p className="mt-5 text-xs text-muted-foreground">Diseñada para iluminación, revestimientos y negocios con catálogo físico.</p></div><DashboardMockup /></div></section>

    <section id="producto" className="border-y border-border bg-card/40 px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="mb-3 text-sm font-medium text-primary">EL FUERTE DE AMAXTECH</p><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">No es solo una tienda online. Es el sistema operativo de tu negocio.</h2><p className="mt-4 leading-relaxed text-muted-foreground">Conecta la vitrina que ve tu cliente con las decisiones que toma tu equipo. Menos herramientas separadas, menos errores y más control del ciclo completo.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3"><Value title="Vende" text="Catálogo con búsqueda, filtros, variantes, precios en USD y Bs, carrito y confirmación por WhatsApp." icon={ShoppingCart} /><Value title="Administra" text="Productos, stock, usuarios, roles, proveedores y solicitudes en un panel diseñado para operar." icon={ShieldCheck} /><Value title="Crece" text="Tasas, cotizaciones, facturación SENIAT y métricas para tomar decisiones rentables." icon={BarChart3} /></div></div></section>

    <section id="segmentos" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="text-center"><p className="mb-3 text-sm font-medium text-primary">UNA PLATAFORMA, SEIS ÁREAS CLAVE</p><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">Todo lo que tu equipo necesita para operar.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{segments.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-border bg-card p-6 transition-colors hover:border-primary/60"><div className="grid size-11 place-items-center rounded-xl bg-secondary text-primary"><Icon /></div><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text}</p></article>)}</div></section>

    <section id="manual" className="mx-5 rounded-3xl border border-accent/30 bg-accent/10 px-6 py-12 lg:mx-auto lg:max-w-7xl lg:px-12"><div className="grid items-center gap-10 lg:grid-cols-[1fr_0.8fr]"><div><div className="mb-5 grid size-12 place-items-center rounded-xl bg-accent text-accent-foreground"><FileText /></div><p className="mb-3 text-sm font-medium text-accent">MANUAL DE USUARIO</p><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">Enséñale a tu cliente todo lo que puede hacer.</h2><p className="mt-4 max-w-xl leading-relaxed text-muted-foreground">Presenta AmaxTech con claridad: desde explorar el catálogo y generar una solicitud, hasta administrar roles, precios, cotizaciones y facturas SENIAT.</p><Button className="mt-7" variant="outline" asChild><a href={manualUrl} target="_blank" rel="noreferrer">Abrir manual completo <ArrowRight data-icon="inline-end" /></a></Button></div><div className="overflow-hidden rounded-2xl border border-border bg-background"><div className="flex items-center justify-between border-b border-border px-4 py-3 text-sm"><span className="font-medium">Guía rápida del sistema</span><FileText className="text-accent" /></div><div className="grid gap-3 p-5 text-sm">{['Catálogo, carrito y solicitudes','Panel administrativo y KPIs','Usuarios, roles y permisos','Cotizaciones y facturación SENIAT','Ajuste masivo de precios'].map((item, i) => <div key={item} className="flex items-center gap-3 rounded-lg bg-card p-3"><span className="font-mono text-xs text-accent">0{i + 1}</span><span>{item}</span></div>)}</div></div></div></section>

    <section id="precios" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 text-sm font-medium text-primary">UNA INVERSIÓN CON RETORNO</p><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">Elige cómo empezar.</h2></div><p className="max-w-sm text-sm leading-relaxed text-muted-foreground">Conoce el sistema, personalízalo para tu operación y ofrece a tus clientes una experiencia profesional.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{[['Esencial','Catálogo + solicitudes','Para comenzar a vender con una tienda propia.'],['Profesional','Operación completa','Para equipos que necesitan administrar y medir.'],['Enterprise','Sistema a tu medida','Para negocios que quieren escalar con control.']].map(([name,tag,desc], i) => <div key={name} className={`rounded-2xl border p-7 ${i === 1 ? 'border-primary bg-primary/10' : 'border-border bg-card'}`}>{i === 1 && <span className="rounded-full bg-primary px-3 py-1 text-xs font-medium text-primary-foreground">Más completo</span>}<h3 className="mt-5 text-xl font-semibold">{name}</h3><p className="mt-2 text-primary">{tag}</p><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{desc}</p><Button className="mt-7 w-full" variant={i === 1 ? 'default' : 'outline'} asChild><a href="#contacto">Solicitar propuesta</a></Button><ul className="mt-7 flex flex-col gap-3 text-sm text-muted-foreground">{['Tienda responsive','Panel administrativo','Soporte de implementación'].map(x => <li key={x} className="flex items-center gap-2"><Check className="text-primary" />{x}</li>)}</ul></div>)}</div></section>

    <section id="faq" className="border-t border-border px-5 py-20 lg:px-8"><div className="mx-auto max-w-3xl"><div className="text-center"><p className="mb-3 text-sm font-medium text-primary">PREGUNTAS FRECUENTES</p><h2 className="text-3xl font-semibold tracking-tight">La información que tu cliente necesita.</h2></div><div className="mt-10 flex flex-col divide-y divide-border border-y border-border">{faqs.map(([q,a], i) => <div key={q} className="py-5"><button className="flex w-full items-center justify-between text-left font-medium" onClick={() => setFaq(faq === i ? null : i)}>{q}<ChevronDown className={`transition-transform ${faq === i ? 'rotate-180 text-primary' : 'text-muted-foreground'}`} /></button>{faq === i && <p className="mt-3 max-w-2xl pr-8 text-sm leading-relaxed text-muted-foreground">{a}</p>}</div>)}</div></div></section>

    <section id="contacto" className="px-5 pb-20 lg:px-8"><div className="mx-auto max-w-5xl rounded-3xl bg-primary px-6 py-14 text-primary-foreground sm:px-12"><div className="grid items-center gap-8 md:grid-cols-[1fr_auto]"><div><p className="mb-3 text-sm font-medium text-primary-foreground/70">CONVIERTE TU OPERACIÓN EN UNA VENTAJA</p><h2 className="max-w-2xl text-3xl font-semibold tracking-tight sm:text-4xl">Haz que tu negocio se vea tan profesional como realmente es.</h2><p className="mt-4 max-w-xl leading-relaxed text-primary-foreground/75">Solicita una demostración y descubre cómo AmaxTech puede convertirse en la plataforma que ofreces a tus clientes.</p></div><form onSubmit={submitLead} className="flex w-full max-w-md flex-col gap-3 sm:flex-row"><input aria-label="Tu email" type="email" required placeholder="tu@email.com" value={email} onChange={e => setEmail(e.target.value)} className="h-11 min-w-0 flex-1 rounded-lg border border-primary-foreground/20 bg-primary-foreground/10 px-4 text-sm outline-none placeholder:text-primary-foreground/50" /><Button className="h-11 bg-primary-foreground text-primary hover:bg-primary-foreground/90">{sent ? 'Solicitud enviada' : 'Solicitar demo'}</Button></form></div></div></section>
    <footer className="border-t border-border px-5 py-7 text-center text-sm text-muted-foreground">© 2026 amaxtech · Catálogo, ventas y gestión administrativa.</footer>
  </main>
}

function Value({ icon: Icon, title, text }: { icon: React.ElementType; title: string; text: string }) { return <article className="rounded-2xl border border-border bg-card p-6"><div className="flex items-center gap-3"><Icon className="text-primary" /><h3 className="text-lg font-semibold">{title}</h3></div><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{text}</p></article> }
function DashboardMockup() { return <div className="relative rounded-2xl border border-border bg-card p-3 shadow-2xl shadow-primary/10"><div className="rounded-xl border border-border bg-background p-4 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">Ingresos del mes</p><p className="mt-1 text-2xl font-semibold">$3.845,20</p></div><span className="rounded-full bg-primary/15 px-2 py-1 text-xs text-primary">+18,4%</span></div><div className="mt-8 flex h-40 items-end gap-2 border-b border-border px-2">{[35,48,42,65,54,72,58,88,76,100,83,96].map((h, i) => <div key={i} style={{ height: `${h}%` }} className={`flex-1 rounded-t-sm ${i > 8 ? 'bg-primary' : 'bg-secondary'}`} />)}</div><div className="mt-5 grid grid-cols-3 gap-3">{[['Solicitudes','27'],['Stock bajo','6'],['Tasa','Bs. 36,82']].map(([a,b]) => <div key={a} className="rounded-lg bg-secondary/60 p-3"><p className="text-[10px] text-muted-foreground">{a}</p><p className="mt-1 text-sm font-medium">{b}</p></div>)}</div></div></div> }
